replica_count: 1

image:
  repository: juliantoro/chatwoot-bot
  tag: latest
  pull_policy: IfNotPresent

service:
  type: ClusterIP
  port: 80

env:
  chatwoot_base_url: "https://your.chatwoot.instance"
  chatwoot_api_key: "your_chatwoot_api_key"
  account_id: "your_account_id"

resources: {}
node_selector: {}
tolerations: []
affinity: {}