apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chatwoot-bot.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "chatwoot-bot.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "chatwoot-bot.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "chatwoot-bot.name" . }}
    spec:
      containers:
        - name: chatwoot-bot
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pull_policy }}
          ports:
            - containerPort: 80
          env:
            - name: CHATWOOT_BASE_URL
              value: {{ .Values.env.chatwoot_base_url }}
            - name: CHATWOOT_API_KEY
              value: {{ .Values.env.chatwoot_api_key }}
            - name: ACCOUNT_ID
              value: {{ .Values.env.account_id | quote }} 
            - name: CHATWOOT_DOMAIN
              value: {{ .Values.env.chatwoot_domain | quote }}
            - name: EVOLUTION_API_URL
              value: {{ .Values.env.evolution_api_url }}
            - name: EVOLUTION_API_TOKEN
              value: {{ .Values.env.evolution_api_token }}
            - name: EVOLUTION_API_INSTANCE
              value: {{ .Values.env.evolution_api_instance }}              